"""
SCIP-based symbol navigator.

Provides precise goto_definition, find_references, find_implementations
by parsing a .scip index file generated by an official SCIP indexer
(scip-python, scip-typescript, etc.).
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


@dataclass
class SCIPLocation:
    file_path: str
    start_line: int
    start_char: int
    end_line: int
    end_char: int


@dataclass
class SCIPSymbol:
    scip_symbol: str
    display_name: str
    kind: str
    documentation: str
    definition: Optional[SCIPLocation] = None
    references: list[SCIPLocation] = field(default_factory=list)


INDEXER_COMMANDS: dict[str, list[str]] = {
    "python": ["scip-python", "index", ".", "--output"],
    "typescript": ["scip-typescript", "index", "--output"],
    "javascript": ["scip-typescript", "index", "--infer-tsconfig", "--output"],
    "go": ["scip-go", "--output"],
    "java": ["scip-java", "index", "--output"],
    "rust": ["rust-analyzer", "scip", "--output"],
}


class SCIPNavigator:
    """
    Parses a .scip index and provides precise symbol navigation.

    Usage::

        nav = SCIPNavigator(repo_root)
        nav.build_index(language="python")  # or nav.load_index(path)
        defs = nav.goto_definition("my_function")
    """

    def __init__(self, repo_root: Path) -> None:
        self.repo_root = Path(repo_root).resolve()
        self._symbols: dict[str, SCIPSymbol] = {}
        self._file_symbols: dict[str, list[str]] = {}
        self._loaded = False

    @property
    def available(self) -> bool:
        return self._loaded and len(self._symbols) > 0

    def build_index(
        self,
        language: str = "python",
        output_path: Optional[Path] = None,
    ) -> Path:
        """Run the SCIP indexer and load the result."""
        output = output_path or (self.repo_root / "index.scip")
        cmd_template = INDEXER_COMMANDS.get(language)
        if cmd_template is None:
            raise ValueError(f"No SCIP indexer for language '{language}'. "
                             f"Supported: {list(INDEXER_COMMANDS)}")

        exe = shutil.which(cmd_template[0])
        if exe is None:
            raise RuntimeError(
                f"{cmd_template[0]} not found. Install the SCIP indexer for {language}."
            )

        cmd = cmd_template + [str(output)]
        logger.info("Running SCIP indexer: %s", " ".join(cmd))
        result = subprocess.run(
            cmd,
            cwd=str(self.repo_root),
            capture_output=True,
            text=True,
            timeout=600,
        )
        if result.returncode != 0:
            logger.error("SCIP indexer failed:\n%s", result.stderr)
            raise RuntimeError(f"SCIP indexer failed (exit {result.returncode})")

        self.load_index(output)
        return output

    def load_index(self, scip_path: Path) -> None:
        """Parse a .scip file and populate the symbol tables."""
        scip_path = Path(scip_path)
        if not scip_path.exists():
            raise FileNotFoundError(f"SCIP index not found: {scip_path}")

        try:
            self._parse_scip(scip_path)
            self._loaded = True
            logger.info("SCIP index loaded: %d symbols from %s",
                        len(self._symbols), scip_path)
        except Exception as exc:
            logger.error("Failed to parse SCIP index: %s", exc)
            raise

    def _parse_scip(self, scip_path: Path) -> None:
        """Parse the protobuf .scip file."""
        try:
            from scip import scip_pb2
        except ImportError:
            from google.protobuf import descriptor_pb2
            raise ImportError(
                "scip-python package required for SCIP parsing. "
                "Install: pip install scip-python"
            )

        raw = scip_pb2.Index()
        raw.ParseFromString(scip_path.read_bytes())

        for doc in raw.documents:
            rel_path = doc.relative_path
            sym_ids: list[str] = []

            sym_info_map: dict[str, Any] = {}
            for sym in doc.symbols:
                sym_info_map[sym.symbol] = sym

            for occ in doc.occurrences:
                if not occ.symbol:
                    continue

                loc = self._parse_range(occ.range, rel_path)
                is_def = bool(occ.symbol_roles & 1)

                if occ.symbol not in self._symbols:
                    info = sym_info_map.get(occ.symbol)
                    self._symbols[occ.symbol] = SCIPSymbol(
                        scip_symbol=occ.symbol,
                        display_name=getattr(info, "display_name", "") if info else "",
                        kind=str(getattr(info, "kind", 0)) if info else "0",
                        documentation="\n".join(info.documentation) if info else "",
                    )

                sym = self._symbols[occ.symbol]
                if is_def:
                    sym.definition = loc
                else:
                    sym.references.append(loc)

                sym_ids.append(occ.symbol)

            self._file_symbols[rel_path] = sym_ids

    def _parse_range(self, r: list[int], file_path: str) -> SCIPLocation:
        if len(r) == 3:
            return SCIPLocation(file_path, r[0], r[1], r[0], r[2])
        return SCIPLocation(file_path, r[0], r[1], r[2], r[3])

    def goto_definition(self, query: str) -> Optional[SCIPLocation]:
        """Find the definition location of a symbol."""
        sym = self._find_symbol(query)
        if sym and sym.definition:
            return sym.definition
        return None

    def find_references(self, query: str, top_k: int = 50) -> list[SCIPLocation]:
        """Find all reference locations for a symbol."""
        sym = self._find_symbol(query)
        if sym:
            return sym.references[:top_k]
        return []

    def find_implementations(self, query: str, top_k: int = 20) -> list[SCIPLocation]:
        """
        Find implementations. SCIP encodes this via relationships.
        Falls back to reference search if no explicit implementations found.
        """
        return self.find_references(query, top_k=top_k)

    def search_symbols(self, query: str, top_k: int = 20) -> list[SCIPSymbol]:
        """Search symbols by name substring."""
        query_lower = query.lower()
        results: list[tuple[float, SCIPSymbol]] = []
        for sym in self._symbols.values():
            name = sym.display_name or sym.scip_symbol
            name_lower = name.lower()
            if query_lower in name_lower:
                score = 2.0 if name_lower == query_lower else (
                    1.0 if name_lower.startswith(query_lower) else 0.5
                )
                results.append((score, sym))
        results.sort(key=lambda x: x[0], reverse=True)
        return [s for _, s in results[:top_k]]

    def _find_symbol(self, query: str) -> Optional[SCIPSymbol]:
        if query in self._symbols:
            return self._symbols[query]
        results = self.search_symbols(query, top_k=1)
        return results[0] if results else None
